version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: voice-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: voice-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}